# Project: Matices
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"D:/Semestre VI/Algoritmos/Dev-Cpp/MinGW32/lib" -L"D:/Semestre VI/Algoritmos/Dev-Cpp/MinGW32/i686-w64-mingw32/lib" -static-libgcc -g3
INCS     = 
CXXINCS  = -I"D:/Semestre VI/Algoritmos/Dev-Cpp/MinGW32/include" -I"D:/Semestre VI/Algoritmos/Dev-Cpp/MinGW32/i686-w64-mingw32/include" -I"D:/Semestre VI/Algoritmos/Dev-Cpp/MinGW32/lib/gcc/i686-w64-mingw32/7.1.0/include" -I"D:/Semestre VI/Algoritmos/Dev-Cpp/MinGW32/lib/gcc/i686-w64-mingw32/7.1.0/include/c++" -I"D:/Semestre VI/Algoritmos/Dev-Cpp/MinGW32/lib/gcc/i686-w64-mingw32/7.1.0/include-fixed" -I"D:/Semestre VI/Algoritmos/Dev-Cpp/MinGW32/lib/gcc/i686-w64-mingw32/7.1.0/include/c++/backward" -I"D:/Semestre VI/Algoritmos/Dev-Cpp/MinGW32/lib/gcc/i686-w64-mingw32/7.1.0/include/c++/i686-w64-mingw32"
BIN      = Matices.exe
CXXFLAGS = $(CXXINCS) -Wall -Wextra -pedantic -g3 -std=c++17
CFLAGS   = $(INCS) -Wall -Wextra -pedantic -g3 -std=c++17
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
